% task2_writeSheet — mark the sixteen newly extracted session x task rows in
% dataTracking.xlsx (Tasks_260824.md Task 2 step 6): Raw Data Extracted = X and
% datPre = the canonical EEGbreathing root, via writeParams with the explicit
% AllowUnextracted/SetRawExtracted options. Verifies each extracted raw file
% exists on disk BEFORE touching the row.

ROOT_CANON = 'R:\Neurology\Zelano_Lab\Lab_Common\AllStudyData\EEGbreathing\';
ROOT = ROOT_CANON;

% id, P.task caller key, raw folder name
ROWS = { ...
 '260227_EEG_NWU_HW', 'breathingTask',      'raw_waveBreathing'; ...
 '260805_EEG_NWU_CA', 'alternating6Blocks', 'raw_alternating6Blocks'; ...
 '260806_EEG_NWU_JH', 'alternating6Blocks', 'raw_alternating6Blocks'; ...
 '260806_EEG_NWU_JH', 'EmotionalMovieTask', 'raw_EmotionalMovieTask'; ...
 '260806_EEG_NWU_MM', 'alternating6Blocks', 'raw_alternating6Blocks'; ...
 '260806_EEG_NWU_MM', 'EmotionalMovieTask', 'raw_EmotionalMovieTask'; ...
 '260807_EEG_NWU_GP', 'alternating6Blocks', 'raw_alternating6Blocks'; ...
 '260807_EEG_NWU_GP', 'EmotionalMovieTask', 'raw_EmotionalMovieTask'; ...
 '260810_EEG_NWU_IS', 'alternating6Blocks', 'raw_alternating6Blocks'; ...
 '260810_EEG_NWU_IS', 'EmotionalMovieTask', 'raw_EmotionalMovieTask'; ...
 '260810_EEG_NWU_AL', 'alternating6Blocks', 'raw_alternating6Blocks'; ...
 '260810_EEG_NWU_AL', 'EmotionalMovieTask', 'raw_EmotionalMovieTask'; ...
 '260811_EEG_NWU_MS', 'alternating6Blocks', 'raw_alternating6Blocks'; ...
 '260811_EEG_NWU_MS', 'EmotionalMovieTask', 'raw_EmotionalMovieTask'; ...
 '260811_EEG_NWU_HK', 'alternating6Blocks', 'raw_alternating6Blocks'; ...
 '260811_EEG_NWU_HK', 'EmotionalMovieTask', 'raw_EmotionalMovieTask'};

for k = 1:size(ROWS, 1)
    [id, taskKey, rawFold] = ROWS{k, :};
    rawFile = fullfile(ROOT, id, 'raw', rawFold, [rawFold '.mat']);
    if ~exist(rawFile, 'file')
        fprintf('SKIP %s / %s: raw file missing (%s)\n', id, taskKey, rawFile);
        continue;
    end
    P = struct('task', taskKey, 'datPre', ROOT_CANON);
    writeParams(P, id, [], 'AllowUnextracted', true, 'SetRawExtracted', true);
end
fprintf('task2_writeSheet: DONE\n');
