% task2_writeLoadScripts — generate the 16 LoadData scripts for the nine new
% EEG_breathing subjects (Tasks_260824.md Task 2 step 3).
%
% Template: LoadData_260109_EEG_NWU_AA.m (the extracted-participant standard).
% Channel mapping measured by batch/task2_probeChannels (2026-08-25):
%   - all recordings fs = 2000 Hz
%   - EEG on CSC33:64 (10-20 order), ECG on CSC25/26/27, photodiode on CSC269
%   - respiration: CSC31 for the 2026-08 subjects (respFrac 0.53-0.83; CSC270 is
%     a dead noise band there); CSC270 for 260227_EEG_NWU_HW (old wiring, no
%     CSC31 data recorded)
%   - JH / MM are single combined recordings: alternating6Blocks first, then
%     EmotionalMovieTask; split = first strong movie photodiode pulse - 120 s
%     (measured: JH first pulse 3525.0 s -> split sample 6,810,000; MM first
%     pulse 3685.3 s -> split sample 7,130,600; both at 2000 Hz)
%   - GP/AL/MS/HK: movie recording is channel-file suffix '_0001'; IS: '_0002'
%     ('_0001' is a 16-s false start). CA has no movie recording.
%
% Writes each script into the subject folder on R: and prints every file written.

ROOT = 'R:\Neurology\Zelano_Lab\Lab_Common\AllStudyData\EEGbreathing';

% id, timestamp, task, suffix, splitSample, segment(pre/post/''), rsp CSC, firstPulseSec
SPECS = { ...
 '260227_EEG_NWU_HW','2026-02-27_13-34-43','waveBreathing','',NaN,'','CSC270',NaN; ...
 '260805_EEG_NWU_CA','2026-08-05_09-29-23','alternating6Blocks','',NaN,'','CSC31',NaN; ...
 '260806_EEG_NWU_JH','2026-08-06_09-23-06','alternating6Blocks','',6810000,'pre','CSC31',3525.0; ...
 '260806_EEG_NWU_JH','2026-08-06_09-23-06','EmotionalMovieTask','',6810000,'post','CSC31',3525.0; ...
 '260806_EEG_NWU_MM','2026-08-06_13-22-23','alternating6Blocks','',7130600,'pre','CSC31',3685.3; ...
 '260806_EEG_NWU_MM','2026-08-06_13-22-23','EmotionalMovieTask','',7130600,'post','CSC31',3685.3; ...
 '260807_EEG_NWU_GP','2026-08-07_09-17-52','alternating6Blocks','',NaN,'','CSC31',NaN; ...
 '260807_EEG_NWU_GP','2026-08-07_09-17-52','EmotionalMovieTask','_0001',NaN,'','CSC31',NaN; ...
 '260810_EEG_NWU_IS','2026-08-10_09-33-29','alternating6Blocks','',NaN,'','CSC31',NaN; ...
 '260810_EEG_NWU_IS','2026-08-10_09-33-29','EmotionalMovieTask','_0002',NaN,'','CSC31',NaN; ...
 '260810_EEG_NWU_AL','2026-08-10_13-25-02','alternating6Blocks','',NaN,'','CSC31',NaN; ...
 '260810_EEG_NWU_AL','2026-08-10_13-25-02','EmotionalMovieTask','_0001',NaN,'','CSC31',NaN; ...
 '260811_EEG_NWU_MS','2026-08-11_09-24-30','alternating6Blocks','',NaN,'','CSC31',NaN; ...
 '260811_EEG_NWU_MS','2026-08-11_09-24-30','EmotionalMovieTask','_0001',NaN,'','CSC31',NaN; ...
 '260811_EEG_NWU_HK','2026-08-11_13-44-38','alternating6Blocks','',NaN,'','CSC31',NaN; ...
 '260811_EEG_NWU_HK','2026-08-11_13-44-38','EmotionalMovieTask','_0001',NaN,'','CSC31',NaN};

% which ids get a single template-named script (one task only)
singleTask = {'260227_EEG_NWU_HW', '260805_EEG_NWU_CA'};

for k = 1:size(SPECS, 1)
    [id, ts, task, sfx, splitS, seg, rspCSC, pulseSec] = SPECS{k, :};
    if ismember(id, singleTask)
        fname = ['LoadData_' id '.m'];
    else
        fname = ['LoadData_' id '_' task '.m'];
    end
    fpath = fullfile(ROOT, id, fname);
    writeScript(fpath, id, ts, task, sfx, splitS, seg, rspCSC, pulseSec);
    fprintf('wrote %s\n', fpath);
end
fprintf('task2_writeLoadScripts: DONE (%d scripts)\n', size(SPECS, 1));

% ============================ generator ============================

function writeScript(fpath, id, ts, task, sfx, splitS, seg, rspCSC, pulseSec)
    fid = fopen(fpath, 'w');
    assert(fid > 0, 'cannot open %s for writing', fpath);
    c = onCleanup(@() fclose(fid));
    w = @(varargin) fprintf(fid, [varargin{1} '\n'], varargin{2:end});

    w('%%%% Channel correspondence');
    w('%% CSC33:64  - EEG (10-20 order, 32 ch)');
    w('%% CSC25/26/27 - ECG1/2/3');
    w('%% %s - respiration (rsp1)', rspCSC);
    w('%% CSC269 - Photodiode (event)');
    w('%%');
    w('%% Generated by batch/task2_writeLoadScripts.m (zelanoLabPreprocessing,');
    w('%% Tasks_260824.md Task 2) on 2026-08-25. Channel mapping verified with');
    w('%% batch/task2_probeChannels.m (see E:\\reprocBackup_260824\\task2_probe).');
    if ~isnan(splitS)
        w('%%');
        w('%% COMBINED RECORDING: alternating6Blocks first, EmotionalMovieTask last.');
        w('%% Split sample %d (= %.1f s at 2000 Hz) = first strong movie photodiode', splitS, splitS/2000);
        w('%% pulse (%.1f s on z-scored CSC269, |z|>3) minus 120 s. This script keeps', pulseSec);
        w('%% the ''%s'' segment for task %s.', seg, task);
    end
    w('');
    w('%%%% path specification and fieldtrip start');
    w('clear');
    w('if exist(''E:\\GitHub\\fieldtrip-20230118'', ''dir'')');
    w('    addpath(''E:\\GitHub\\fieldtrip-20230118'')   %% lab desktop');
    w('else');
    w('    addpath(''G:\\My Drive\\GitHub\\fieldtrip-20230118'')');
    w('end');
    w('');
    w('%%add path to lab matlab code with import function ReadNCS');
    w('addpath(''R:\\Neurology\\Zelano_Lab\\Lab_Common\\Matlab_Code'') %%PC PATH');
    w('');
    w('ft_defaults');
    w('%%%% Edit these file variables as needed');
    w('');
    w('%%subject''s folder:');
    w('subID = ''%s'';', id);
    w('expFolder = ''EEGbreathing'';');
    w('');
    w('%%atlas generated time stamp:');
    w('timStamp = ''%s'';', ts);
    w('');
    w('%%specify which channels you want for this subject:');
    w('CSClist = arrayfun(@(x) [''CSC'' num2str(x)], 33:64, ''uniformoutput'', false);');
    w('CSClist{end+1} = ''CSC25'';');
    w('CSClist{end+1} = ''CSC26'';');
    w('CSClist{end+1} = ''CSC27'';');
    w('CSClist{end+1} = ''%s'';', rspCSC);
    w('CSClist{end+1} = ''CSC269'';');
    w('');
    w('ReadableLabs = {''Fp1'', ''Fz'' , ''F3'' , ''F7'' , ''FT9'', ''FC5'', ''FC1'', ...');
    w('                ''C3'' , ''T7'' , ''TP9'', ''CP5'', ''CP1'', ''Pz'' , ''P3'' , ...');
    w('                ''P7'' , ''O1'' , ''Oz'' , ''O2'' , ''P4'' , ''P8'' , ''TP10'',...');
    w('                ''CP6'', ''CP2'', ''Cz'' , ''C4'' , ''T8'' ,''FT10'', ''FC6'', ...');
    w('                ''FC2'', ''F4'' , ''F8'' , ''Fp2'', ...');
    w('                ''ECG1'', ''ECG2'', ''ECG3'', ...');
    w('                ''rsp1'', ''event''};');
    w('');
    w('%%specify output task names and input suffix channel IDs:');
    w('taskList = cell(1,2);');
    w('taskList(1,:) = {''%s'', ''%s''};', task, sfx);
    if ~isnan(splitS)
        w('');
        w('%%combined-recording split (see header):');
        w('splitSample = %d;', splitS);
        w('keepSegment = ''%s'';   %% ''pre'' = alternating6Blocks, ''post'' = EmotionalMovieTask', seg);
    end
    w('');
    w('%%%% Hard coded parts of file path generation (probably doesn''t need edit)');
    w('');
    w('pre = ''R:\\Neurology\\Zelano_Lab\\Lab_Common\\AllStudyData\\''; %%PC PATH');
    w('');
    w('%%make prefix into file bits');
    w('pre = regexp(pre, ''[\\\\/]'', ''split'');');
    w('');
    w('%%append the experiment and subject folders to the filepath:');
    w('L = length(pre);');
    w('pre{L+1} = expFolder;');
    w('pre{L+2} = subID;');
    w('%%standard name for raw data subfolder:');
    w('rawFold = ''AtlasData'';');
    w('');
    w('%%%% Load Data');
    w('warning(''off'',''all'')');
    w('allDat = struct;');
    w('for ii = 1:size(taskList,1)');
    w('    disp([''loading: '' taskList{ii,1}])');
    w('    allDat(ii).ncs_labels = cellfun(@(x) strcat(x, taskList{ii,2}), ...');
    w('                                CSClist, ''uniformoutput'', false);');
    w('    allDat(ii).out_labels = ReadableLabs;');
    w('    allDat(ii).rawdata = ReadNCS(fullfile(pre{:}, rawFold, timStamp),...');
    w('                                allDat(ii).ncs_labels);');
    w('    allDat(ii).taskName = taskList{ii, 1};');
    w('end');
    if ~isnan(splitS)
        w('');
        w('%%%% cut the combined recording to the segment this script''s task covers');
        w('for ii = 1:size(taskList,1)');
        w('    nS = size(allDat(ii).rawdata.trial{1}, 2);');
        w('    if strcmp(keepSegment, ''pre'')');
        w('        keep = 1:min(splitSample-1, nS);');
        w('    else');
        w('        keep = splitSample:nS;');
        w('    end');
        w('    allDat(ii).rawdata.trial{1} = allDat(ii).rawdata.trial{1}(:, keep);');
        w('    allDat(ii).rawdata.time{1}  = allDat(ii).rawdata.time{1}(keep);');
        w('    if isfield(allDat(ii).rawdata, ''sampleinfo'')');
        w('        allDat(ii).rawdata.sampleinfo = [1 numel(keep)];');
        w('    end');
        w('end');
    end
    w('');
    w('%%%% Save Data');
    w('');
    w('for ii = 1:size(taskList,1)');
    w('    curFolder = [''raw_'' allDat(ii).taskName];');
    w('    mkdir(fullfile(pre{:}, ''raw'', curFolder));');
    w('');
    w('    curDat = struct;');
    w('    curDat.ncslabels = allDat(ii).ncs_labels;');
    w('    curDat.rawData = allDat(ii).rawdata;');
    w('    curDat.outLabs = allDat(ii).out_labels;');
    w('');
    w('    curName = [''raw_'' allDat(ii).taskName ''.mat''];');
    w('');
    w('    save(fullfile(pre{:},''raw'',  curFolder, curName), ''curDat'', ''-v7.3'')');
    w('');
    w('end');
end
