% task10_validateV3 — offline validation of engine v3 (300-ms smoothing, 30-s
% movmad windowed normalization, middle-50% onset band correction, MS leak
% blanking) against the SPECIFIC minutes flagged in the 2026-08 QC review
% (breath_detection_qc_notes.md). Loads each final, re-segments its stored
% trace, and plots the flagged minutes (absolute minute bins matching the
% original qc_* figure ylabels). Nothing is saved to preProc.

outDir = 'E:\reprocBackup_260824\v3check';
if ~exist(outDir, 'dir'), mkdir(outDir); end

% {id, taskKey, glob, minutes, blankBelowFrac ([]=none), tag}
C = { ...
 % --- whole-minute dropout (were GLOBAL-mode finals) ---
 '251009_EEG_NWU_SM',   'breathingTask', '_breathing*.mat', [2 4 5 52],   [], 'dropout'; ...
 '251205_EEG_NWU_AK',   'breathingTask', '_breathing*.mat', [1 2 3 33],   [], 'dropout'; ...
 '251202_EEG_NWU_GJ',   'breathingTask', '_breathing*.mat', [3 4 5 83],   [], 'dropout+trough'; ...
 '251027_EEG_NWU_AS',   'breathingTask', '_breathing*.mat', [45 68],      [], 'dropout'; ...
 '260625_OBE_NWU_HM_2', 'breathingTasks_separate', '_breathingTasks_separate*.mat', [3 26 28 32], [], 'dropout'; ...
 '251027_Dupi_NMH_DL_1','breathingTasks_separate', '_breathingTasks_separate*.mat', [2 3 4 6],    [], 'dropout'; ...
 % --- residual misses in windowed sessions ---
 '260805_EEG_NWU_CA',   'alternating6Blocks', '_alternating6Blocks*.mat', [11 31 33], [], 'windowed-miss'; ...
 '260806_EEG_NWU_MM',   'alternating6Blocks', '_alternating6Blocks*.mat', [3 42 50 59], [], 'windowed-miss+trough'; ...
 '260806_EEG_NWU_JH',   'alternating6Blocks', '_alternating6Blocks*.mat', [5 9 49],   [], 'windowed-miss'; ...
 '260811_EEG_NWU_HK',   'alternating6Blocks', '_alternating6Blocks*.mat', [43 50 52], [], 'windowed-miss'; ...
 '260810_EEG_NWU_IS',   'alternating6Blocks', '_alternating6Blocks*.mat', [4 40],     [], 'windowed-miss'; ...
 % --- trough / peak onset bias ---
 '250929_Dupi_NMH_GH_2','breathingTask', '_breathing*.mat', [1 2 3],    [], 'trough'; ...
 '251030_Dupi_NMH_DB_2','breathingTask', '_breathing*.mat', [8 9 13],   [], 'trough'; ...
 '251003_EEG_NWU_TI',   'breathingTask', '_breathing*.mat', [22 39 68 70], [], 'trough+miss'; ...
 '251113_EEG_NWU_GH',   'breathingTask', '_breathing*.mat', [2 12],     [], 'trough'; ...
 '251009_EEG_NWU_JM',   'breathingTask', '_breathing*.mat', [46 47],    [], 'trough'; ...
 '251110_EEG_NWU_GA',   'breathingTask', '_breathing*.mat', [11 36 47], [], 'trough+peak'; ...
 '260109_EEG_NWU_AA',   'breathingTask', '_breathing*.mat', [10 39],    [], 'peak'; ...
 '251110_Dupi_NMH_PC_1','breathingTask', '_breathing*.mat', [3 14 15],  [], 'peak+miss'; ...
 '260720_OBE_NWU_KA_2', 'breathingTasks_separate', '_breathingTasks_separate*.mat', [1 2], [], 'peak'; ...
 '250929_Dupi_NMH_GH_1','breathingTasks_separate', '_breathingTasks_separate*.mat', [1 2], [], 'peak'; ...
 '250929_Dupi_NMH_GH_1','breathingTask', '_breathing*.mat', [16 27 28], [], 'trough+mid'; ...
 % --- double peak / ragged / over-detection (smoothing) ---
 '250904_OBE_NWU_TI_1', 'breathingTask', '_breathing*.mat', [21 22 23], [], 'double-peak'; ...
 '250912_EEG_NWU_JN',   'breathingTask', '_breathing*.mat', [8 11],     [], 'double-peak+trough'; ...
 '251111_EEG_NWU_VW',   'breathingTask', '_breathing*.mat', [9 65],     [], 'ragged'; ...
 '250811_Dupi_NMH_TPB_1','breathingTask','_breathing*.mat', [2 3 5],    [], 'over-detect'; ...
 '251027_Dupi_NMH_DL_1','breathingTask', '_breathing*.mat', [21 4],     [], 'over-detect'; ...
 '251008_EEG_NWU_JC',   'breathingTask', '_breathing*.mat', [6 7 17 54], [], 'noise+subtle'; ...
 % --- movie scattered misses ---
 '260806_EEG_NWU_JH',   'emotionalMovieTask', '_EmotionalMovieTask*.mat', [6 17 25], [], 'movie-miss'; ...
 '260806_EEG_NWU_MM',   'emotionalMovieTask', '_EmotionalMovieTask*.mat', [4 22 25], [], 'movie-miss'; ...
 '260807_EEG_NWU_GP',   'emotionalMovieTask', '_EmotionalMovieTask*.mat', [1 4 6],   [], 'movie-miss'; ...
 '260810_EEG_NWU_AL',   'emotionalMovieTask', '_EmotionalMovieTask*.mat', [4 12 15], [], 'movie-miss'; ...
 '260810_EEG_NWU_IS',   'emotionalMovieTask', '_EmotionalMovieTask*.mat', [5 16 17], [], 'movie-miss'; ...
 '260811_EEG_NWU_HK',   'emotionalMovieTask', '_EmotionalMovieTask*.mat', [11 29 31], [], 'movie-miss'; ...
 '260811_EEG_NWU_MS',   'emotionalMovieTask', '_EmotionalMovieTask*.mat', [9 20 26], 0.10, 'movie-miss+blank'; ...
 % --- MS exclusion ---
 '260811_EEG_NWU_MS',   'alternating6Blocks', '_alternating6Blocks*.mat', [6 7 8 37], 0.10, 'blank-leak'; ...
 % --- no-regression controls ---
 '260807_EEG_NWU_GP',   'alternating6Blocks', '_alternating6Blocks*.mat', [21 39], [], 'control'; ...
 '251030_Dupi_NMH_DB_1','breathingTask', '_breathing*.mat', [1 4],  [], 'control'; ...
 '251002_Dupi_NMH_AB_1','breathingTask', '_breathing*.mat', [4 8],  [], 'control'; ...
 '251008_EEG_NWU_GM',   'breathingTask', '_breathing*.mat', [8 12], [], 'control'; ...
 '250819_EEG_NWU_ZL',   'breathingTask', '_breathing*.mat', [17 34], [], 'control'; ...
 '250723_EEG_NWU_BK',   'breathingTask', '_breathing*.mat', [5 17], [], 'control'};

for k = 1:size(C, 1)
    [id, tkey, glb, mins, blankF, tag] = C{k, :};
    try
        cfg = applyParams(tkey, 'main');
        si = find(strcmp(cfg.sessionIDs, id), 1);
        hits = dir(fullfile(cfg.root{si}, id, 'preProc', [id glb]));
        s = load(fullfile(hits(1).folder, hits(1).name));
        fn = fieldnames(s); od = s.(fn{1}); clear s

        isRsp = cellfun(@(x) contains(x, 'rsp'), od.labels);
        rsp = od.data(isRsp, :);
        rsp = rsp(od.rspIDX, :) .* od.rspFlip;
        fs = od.fs;
        nOld = size(od.bmObj, 1);

        bmNew = segmentBreaths_breathMetrics(rsp, fs, [], blankF);
        onsets = round(bmNew(:, 2) * fs);
        onsets = onsets(onsets >= 1 & onsets <= numel(rsp));
        fprintf('V3 %-24s %-22s [%s]: %d -> %d breaths\n', id, tkey, tag, nOld, size(bmNew, 1));

        nP = numel(mins);
        fig = figure('Visible', 'off', 'Position', [10 10 1500 230 * nP]);
        for b = 1:nP
            i0 = (mins(b) - 1) * 60 * fs + 1; i1 = min(mins(b) * 60 * fs, numel(rsp));
            if i0 >= i1, continue; end
            t = (i0:i1) / fs;
            subplot(nP, 1, b); hold on
            plot(t, rsp(i0:i1), 'k', 'LineWidth', 0.75);
            oi = onsets(onsets >= i0 & onsets <= i1);
            plot(oi / fs, rsp(oi), 'rv', 'MarkerFaceColor', 'r', 'MarkerSize', 6);
            xlim([t(1) t(end)]); ylabel(sprintf('min %d', mins(b)));
            if b == 1
                title(sprintf('%s %s [%s] V3: n=%d (was %d)', ...
                    strrep(id, '_', '\_'), tkey, tag, size(bmNew, 1), nOld));
            end
        end
        saveas(fig, fullfile(outDir, sprintf('v3_%s_%s.jpg', tkey, id)));
        close(fig);
        clear od rsp
    catch ME
        fprintf('V3 FAIL %s %s: %s\n', id, tkey, ME.message);
    end
end
fprintf('task10_validateV3: DONE\n');
